### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/eslint-plugin-jquery#5]
Blockers:
- [x] Landed upstream's dgraham/eslint-plugin-jquery#20 dgraham/eslint-plugin-jquery#23 dgraham/eslint-plugin-jquery#25 dgraham/eslint-plugin-jquery#26
- [x] Do we want to land dgraham/eslint-plugin-jquery#21?
- [x] Decide on and fix #3
- [x] Decide on a versioning scheme. Does `1.3.2-wmf.1` work for our fork?

**Comment by jdforrester** [comment]
@edg2s @Krinkle comments welcome.

**Comment by jdforrester** [comment]
Do we also want to do #6 and #7?

**Comment by edg2s** [comment]
>  Do we want to land dgraham#21?

That's no-is-array, which has already been merged.

> Do we also want to do #6 and #7?

Not as a blocker to a first release.

**Comment by ljharb** [comment]
v1.5.0 turned out to be a breaking change - please revert 
https://github.com/dgraham/eslint-plugin-jquery/pull/20 and the peer dep change in a v1.5.1.

See https://github.com/dgraham/eslint-plugin-jquery/issues/32

**Comment by jdforrester** [comment]
> v1.5.0 turned out to be a breaking change - please revert
> [dgraham#20](https://github.com/dgraham/eslint-plugin-jquery/pull/20) and the peer dep change in a v1.5.1.
> 
> See [dgraham#32](https://github.com/dgraham/eslint-plugin-jquery/issues/32)

Hey there,

I don't think we landed that – see https://github.com/wikimedia/eslint-plugin-jquery/blob/master/package.json#L21

That said, we're probably going to re-label this fork as its own thing. Note that subsequent patches like https://github.com/wikimedia/eslint-plugin-jquery/commit/58de3850332413b16503c0153fd39255f9875ddc have made major changes to our version of this code, so if you're integrating tightly with it you'd also have issues.

**Comment by ljharb** [comment]
ah, i'm using `eslint-plugin-jquery`, so if that's not your package, disregard :-)

(but for future reference, peer deps should be declared, and peer dep changes are part of your api)
